### ISSUE TITLE
Cannot open python operation file in PythonAPI/examples

### ISSUE THREAD

**Issue by sunchongren** [HARPLab/DReyeVR#19] opened 2022-04-26 18:14 UTC
I encountered another question after I start the application from the path ```E:\carla\Build\UE4Carla\0.9.13-1-g8854804f4-dirty\WindowsNoEditor```

      ./CarlaUE4.exe -vr
The error occurs when I want to run any python operation file such as DReyeVR_AI.py or dynamic_weather.py, it failed. The error code is:

  File "DReyeVR_AI.py", line 140, in main
    ego_vehicle.set_autopilot(False, traffic_manager.get_port())
UnboundLocalError: local variable 'ego_vehicle' referenced before assignment
 
Any possible reason for this?

**Comment by GustavoSilvera** [comment] 2022-04-26 18:19
Hi @sunchongren It looks like this execution path only occurs if the `try` block fails to execute. You should be able to see what the exception was by including 
```python
except Exception as e:
        print(e)
```
between the `try` and `finally` in `DReyeVR_AI.py`:139. 

The exception should be informative as to why the block failed to run and led to the `finally` block.

**Comment by GustavoSilvera** [comment] 2022-04-26 18:24
This means that the client did connect to the simulator in time. Do you have the simulator running simultaneously?

**Comment by sunchongren** [comment] 2022-04-26 18:24
> 

However, the server side is already started if I understand it right by excuting

    ./CarlaUE4.exe

**Comment by GustavoSilvera** [comment] 2022-04-26 18:27
Right, you start the server by running the `CarlaUE4.exe` executable (and you run it in vr with `-vr` flag). As long as the server is running, I'm not sure why you are getting this client connection error. Can you give me some more information:
- What framerate is the simulator running at (if its too slow, maybe increase the timeout duration with `client.set_timeout(x)`)?
- What python instance are you using for this?
- Do you have any other processes running on port `127.0.0.1:2000`? this might be the case if you have lingering instances of CarlaUE4.exe running but frozen. 
  - In this case, you can go into `Task Manager` -> `Details` and end the CarlaUE4.exe process

**Comment by sunchongren** [comment] 2022-04-26 20:13
Hey Gustavo, for the questions above:

1. I tried to use a large number as timeout, but it was not working
2. I am using python 3.8 in conda env
3. The weird thing here is when I run ./CarlaUE4.exe, I cannot find the tcp port information from cmd prompt (netstat), I can only find the process of ```CarlaUE4-shipping.exe``` running on another unrelated port
![image](https://user-images.githubusercontent.com/92778466/165384322-57718dea-7bef-4c2b-8e92-b71ae9dab127.png)

**Comment by GustavoSilvera** [comment] 2022-04-26 20:24
Interesting, ok you should kill all other instances of CarlaUE4 and continue from there. 

Have you tried rebooting your system then trying again?

**Comment by sunchongren** [comment] 2022-04-27 18:19
Rebooting didnt solve the problem.
A interesting thing I noticed is that when I run python on wsl, none of python file works.
However, when I use cmd prompt, some python scripts worked (dynamic_weather, DReyeVR-AI), and some not (generate_veicle, manual_control)

**Comment by sunchongren** [comment] 2022-04-27 18:29
So I think the possible reason is I used wsl?
But something I am confused about is, after ```make package``` for DReyeVR, is some python script disabled?

**Comment by GustavoSilvera** [comment] 2022-04-27 18:36
Right, sorry for any confusion, but yes you are expected to use windows python `python.exe` rather than linux python `python` (bash/WSL) for the CARLA interactions. 

The main reason we use WSL is to clone the repo and install the files over the CARLA installation. Then you can do everything in cmd prompt.

There should not be python scripts disabled for `make package`? Can you be more specific on what's going on?

**Comment by sunchongren** [comment] 2022-04-27 19:14
For ```generate_traffic.py```:
![image](https://user-images.githubusercontent.com/92778466/165602247-c97b90eb-1152-44a8-9569-bb265ad2d604.png)

**Comment by GustavoSilvera** [comment] 2022-04-27 19:55
Thanks for the insight! Most of those scripts you posted have not been extensively tested by us so we don't support them (mostly those that spawn their own ego-vehicle, such as vehicle_physics, gallery, and manual control)

However, the `schematic_mode.py` script should work.

In total we have tested and verified these scripts work:

`start_recording.py` (starts recording a session)
`start_replaying.py` (starts replaying a session)
`show_recorder_file_info.py` (converts the binary recordings to a human readable format)
`DReyeVR_AI.py` (enables the traffic-manager for DReyeVR autopilot)
`DReyeVR_logging.py` (prints all the eye tracker data to screen, or logs to ros if using rospy)
`schematic_mode.py` (wrapper over `no_rendering_mode` to draw ego vehicle)
`dynamic_weather.py` (changes the weather)

**Comment by sunchongren** [comment] 2022-04-27 20:02
Thank you so much Gustavo, then I think my problem solved. 
For the failure of ```schematic_mode.py```:
![image](https://user-images.githubusercontent.com/92778466/165621547-e19f762f-82b3-489f-a33e-7474be32403d.png)

**Comment by GustavoSilvera** [comment] 2022-04-27 20:06
Ah okay, sounds like a duplicate of #12 and I believe the solution has to do with you needing to rebuild the PythonAPI.

To do this run `make PythonAPI` in the Carla folder (this will build the DReyeVR-compatible version of the PythonAPI)

**Comment by sunchongren** [comment] 2022-04-27 20:07
Thanks!

**Comment by sunchongren** [comment] 2022-04-29 02:34
@GustavoSilvera It is still not working. Trying to search more possible reasons

**Comment by sunchongren** [comment] 2022-04-29 02:38
![image](https://user-images.githubusercontent.com/92778466/165877488-baa47efe-5a7e-4024-9af8-efcbf1c34748.png)
Every time I tried to ```make PythonAPI``` and ```make package```,
This error occurs, but it seems the build is succeed.

**Comment by GustavoSilvera** [comment] 2022-04-29 03:09
Hmm, try cleaning everything and removing the old `.egg` from the original PythonAPI build. Then you should be able to rebuild PythonAPI without errors. Can you upload a build log?

**Comment by sunchongren** [comment] 2022-04-29 03:30
What do you mean clean everything @GustavoSilvera

**Comment by GustavoSilvera** [comment] 2022-04-29 03:44
try `make clean`

**Comment by sunchongren** [comment] 2022-04-29 04:25
Unfortunately ```schematic_mode.py``` is still not working. Will try more things tommorow

**Comment by sunchongren** [comment] 2022-04-29 04:26
But the interesting thing is ```no_rendering_mode.py``` do work

**Comment by sunchongren** [comment] 2022-04-29 04:30
And the other thing I don't understand is for the error: ```Assertion failed: px != 0, file C:\workspace\carla\Build\boost-1.72.0-install\include\boost/smart_ptr/shared_ptr.hpp, line 734```. The address in C:\ is even not exist.

**Comment by SteadyBits** [comment] 2022-05-05 15:25
> start_recording


> ![image](https://user-images.githubusercontent.com/92778466/165877488-baa47efe-5a7e-4024-9af8-efcbf1c34748.png) Every time I tried to `make PythonAPI` and `make package`, This error occurs, but it seems the build is succeed.

I got this error when trying to build carla. 1.) Ensure that "wheel" is installed. You can do "pip install wheel" if it's not installed. 2.) Check to ensure that the "wheel" installation path is added to PYTHONPATH in your environment variables. Check "wheel" installation path by running "pip show wheel".

**Comment by sunchongren** [comment] 2022-05-05 17:53
> You are absolutely correct. Thanks!
@GustavoSilvera The problem solved by reinstall wheel.

**Comment by GustavoSilvera** [comment] 2022-05-18 00:02
@sunchongren Do you have any more updates with this issue? We included some related help in our [F.A.Q page](https://github.com/HARPLab/DReyeVR/wiki/Frequently-Asked-Questions).

**Comment by sunchongren** [comment] 2022-05-18 00:21
> 

Yes it is solved. Thanks.

**Closed** 2022-05-18 00:25 UTC
