### ISSUE TITLE
The vehicle moves left & right instead of straight even when the steering wheel is at a fixed position

### ISSUE THREAD

**Issue by Shroculus** [HARPLab/DReyeVR#8] opened 2022-02-23 20:13 UTC
Hi team,

**CARLA version:** 0.9.13

**Platform/OS:** Windows 10 (Version 21H2)

**Problem you have experienced:** I have installed the DReyeVR without any error but when I try to drive, the vehicle doesn't go forward in a straight line even when I hold steering wheel in a fixed direction. Also, I don't see steering wheel move in the virtual environment. 

**Steering Wheels & Pedals:** I have Logitech 920 which is installed and works fine

**Steps to reproduce:**

I followed exact same DReyeVR installation command summary:

NOTE: On windows, this can almost all be done in WSL, except the make commands which need
to be done in the "Windows x64 Native Tools Command Prompt for VS 2019"
mkdir CarlaDReyeVR && cd CarlaDReyeVR # doing everything in this "CarlaDReyeVR" directory **(Executed this command)**

#####################################################
#####################################################
Linux: https://carla.readthedocs.io/en/0.9.13/build_linux/#unreal-engine
Windows: https://carla.readthedocs.io/en/0.9.13/build_windows/#unreal-engine

#####################################################
#####################################################
Linux: https://carla.readthedocs.io/en/0.9.13/build_linux/
Windows: https://carla.readthedocs.io/en/0.9.13/build_windows/
git clone https://github.com/carla-simulator/carla -b 0.9.13
cd carla
./Update.sh
make PythonAPI && make launch (This was executed in X64 command prompt)

#####################################################
#####################################################
(optional) install SRanipal (https://developer.vive.com/resources/vive-sense/eye-and-facial-tracking-sdk/download/latest/)
mv /PATH/TO/SRANIPALPLUGIN/SDK/03_Unreal/Plugins/SRanipal Unreal/CarlaUE4/Plugins/ # install to carla (left out the SRanipal)

(optional) install LogitechWheelPlugin
git clone https://github.com/HARPLab/LogitechWheelPlugin
mv LogitechWheelPlugin/LogitechWheelPlugin Unreal/CarlaUE4/Plugins/ # install to carla

cd .. # back to main directory

#####################################################
#####################################################
(optional) while you don't NEED scenario runner, it is certainly useful from a research pov
git clone https://github.com/carla-simulator/scenario_runner -b v0.9.13

#####################################################
#####################################################
git clone https://github.com/HARPLab/DReyeVR
cd DReyeVR
make all CARLA=../carla SR=../scenario_runner 
or equivalently
make carla CARLA=../carla 
make sr SR=../scenario_runner 
make patch-sranipal CARLA=../carla
cd ..

#####################################################
#####################################################
cd carla
make launch # launch in editor **(All the make commands were again executed in X64 command prompt)**
make package # create an optimized package
make check # run Carla unit tests

To check if I have installed the latest carla I ran the git command and the below is the screenshot for the same:

![image](https://user-images.githubusercontent.com/85901551/155399756-2c94bc5e-e4a4-4e00-bc5d-b4011f45b71d.png)

To check if I have installed the DReyeVR from main I ran the git command and the below is the screenshot for the same:

![image](https://user-images.githubusercontent.com/85901551/155403674-55034c96-a707-4831-ae5d-19d447df7d2d.png)

The pedals works intermittently when I launch the package or even from the Unreal editor in VR preview mode. Also, attaching the log file for your reference. 
[CarlaUE4.log](https://github.com/HARPLab/DReyeVR/files/8127525/CarlaUE4.log)

Any help is appreciated. Thank you in advance.

**Comment by GustavoSilvera** [comment] 2022-02-23 22:24
Hi, so judging by the logs it looks like the installation was successful and Carla+DReyeVR was running successfully. 

Can you further describe what the problem is with the intermittent pedals? We had an issue with this in an earlier version of the software but have recently updated main with fixes to the logitech+keyboard input conflicts, but I'm not sure if these are similar to the errors you are having. 

For example, when you have both the pedals and keyboard connected, do the keyboard inputs (WASD) work while the logitech pedals don't? Or vice versa? Or does the logitech wheel input simply disconnect and reconnect after some time?

**Comment by ajdroid** [comment] 2022-02-24 06:22
For the issue of the vehicle moving left & right instead of straight, it'd be useful if you could provide a screen recording of what is happening for clarity.

**Comment by Shroculus** [comment] 2022-02-24 17:19
> Hi, so judging by the logs it looks like the installation was successful and Carla+DReyeVR was running successfully.
> 
> Can you further describe what the problem is with the intermittent pedals? We had an issue with this in an earlier version of the software but have recently updated main with fixes to the logitech+keyboard input conflicts, but I'm not sure if these are similar to the errors you are having.
> 
> To update to the latest version of DReyeVR main do:
> 
> ```shell
> cd DReyeVR/
> git pull origin main
> 
> # check DReyeVR is the latest version:
> git log | head
> 
> make install CARLA=../carla/
> ```
> 
> For example, when you have both the pedals and keyboard connected, do the keyboard inputs (WASD) work while the logitech pedals don't? Or vice versa? Or does the logitech wheel input simply disconnect and reconnect after some time?

@GustavoSilvera Yes, at times when the keyboard works, pedal dont and vice versa. the problem is intermittent.

**Comment by Shroculus** [comment] 2022-02-24 17:31
> Okay thanks for the recordings, we'll be looking at them and further diagnosing the problem. In the meantime, would you mind providing the output of
> 
> ```shell
> git log | head
> ```
> 
> in your `bash` terminal? This will help us see what version of DReyeVR you are on.

Below is the output:

![image](https://user-images.githubusercontent.com/85901551/155576528-ec03d6f6-e4f6-4b10-93f6-f1082c7150af.png)

**Comment by GustavoSilvera** [comment] 2022-02-24 17:41
Interesting, ok thanks. So you are on the latest version of DReyeVR (and you did run `make install CARLA=../carla` on this latest version?) and the wheel setup still isn't working.

When you unplug the Logitech device, does the keyboard work normally?

What I believe may be happening is that (since our development has been on the Logitech G923) your G920 hardware might have different button/axis mappings for the hardware. This is somewhat difficult to diagnose because the documentation on the LogitechPlugin project is scarce, therefore we created a Logitech input logger that I'd like you to run alongside DReyeVR:

in `DReyeVR/EgoInputs.cpp` please uncomment line 429 which should look like this:
```c++
    // LogLogitechPluginStruct(WheelState);
```

Then, build and run DReyeVR to isolate the correct input mappings. We've found that manipulating a small number of buttons/axes per run (and reading the corresponding logs) got us closer to mapping our hardware, so if you could do that and provide the logs that would be great.

**Comment by Shroculus** [comment] 2022-02-24 17:49
> Interesting, ok thanks. So you are on the latest version of DReyeVR (and you did run `make install CARLA=../carla` on this latest version?) and the wheel setup still isn't working.
> 
> When you unplug the Logitech device, does the keyboard work normally?
> 
> What I believe may be happening is that (since our development has been on the Logitech G923) your G920 hardware might have different button/axis mappings for the hardware. This is somewhat difficult to diagnose because the documentation on the LogitechPlugin project is scarce, therefore we created a Logitech input logger that I'd like you to run alongside DReyeVR:
> 
> in `DReyeVR/EgoInputs.cpp` please uncomment line 429 which should look like this:
> 
> ```c++
>     // LogLogitechPluginStruct(WheelState);
> ```
> 
> Then, build and run DReyeVR to isolate the correct input mappings. We've found that manipulating a small number of buttons/axes per run (and reading the corresponding logs) got us closer to mapping our hardware, so if you could do that and provide the logs that would be great.

So you are on the latest version of DReyeVR (and you did run make install CARLA=../carla on this latest version?) and the wheel setup still isn't working. - **Yes, I did and checked again it still continues with the same behavior as before.**

When you unplug the Logitech device, does the keyboard work normally? -  **Yes, the keyboard works normally even when the logitech is unplugged.** 

Okay, I will try the suggested and keep you updated.

**Comment by Shroculus** [comment] 2022-02-24 21:46
Here is the log after uncommenting the line, building it and then launching it again as suggested.

[CarlaUE4.log](https://github.com/HARPLab/DReyeVR/files/8136586/CarlaUE4.log)

**Comment by GustavoSilvera** [comment] 2022-02-25 00:13
Hmm... This doesn't have the logitech logs that we expect. There should be things like "Logging joystick at t=xyz" updating on every tick when you move the logitech wheel and pedals. We will be investigating this issue more tomorrow with our own setup. 

For now, see if you can get `UE_LOG` values for the `WheelState` values to show in the `LogitechWheelUpdate` such as:
```c++
UE_LOG(LogTemp, Log, TEXT("Logitech Wheel rotation: %.3f"), WheelState->lX);
```

**Comment by GustavoSilvera** [comment] 2022-02-26 03:58
Hi again, upon further examination we found that the logitech debug prints should be working as expected, but for ease of use we added a new flag in the config file (`Config/DReyeVRConfig.ini`) in the new `[Hardware]` section for easily enabling/disabling these debug messages at runtime. We also added some other changes that will be merged with main soon. 

For now, can you switch DReyeVR to the [`dev`](https://github.com/HARPLab/DReyeVR/tree/dev) branch and install over Carla this way:
```bash
cd DReyeVR/
git checkout dev
git pull origin dev
...
make install CARLA=../carla/
```

Then in the Carla directory, locate the config file at `Unreal/CarlaUE4/Config/DReyeVRConfig.ini` and ensure the new flag at the bottom (`LogUpdates`) is present and set to `True`. 

With this version, you should see new logs such as your logitech device name and button/axis trigger events in the updated logfile.

**Comment by Shroculus** [comment] 2022-03-04 20:42
> Hi again, upon further examination we found that the logitech debug prints should be working as expected, but for ease of use we added a new flag in the config file (`Config/DReyeVRConfig.ini`) in the new `[Hardware]` section for easily enabling/disabling these debug messages at runtime. We also added some other changes that will be merged with main soon.
> 
> For now, can you switch DReyeVR to the [`dev`](https://github.com/HARPLab/DReyeVR/tree/dev) branch and install over Carla this way:
> 
> ```shell
> cd DReyeVR/
> git checkout dev
> git pull origin dev
> ...
> make install CARLA=../carla/
> ```
> 
> Then in the Carla directory, locate the config file at `Unreal/CarlaUE4/Config/DReyeVRConfig.ini` and ensure the new flag at the bottom (`LogUpdates`) is present and set to `True`.
> 
> With this version, you should see new logs such as your logitech device name and button/axis trigger events in the updated logfile.

Hi @GustavoSilvera! Thank you for your response. I apologize for the delay in getting back to you with the update. I did what you asked by switching the DReyeVR to the dev and below is the reference for the same. 

[Ubuntu_Commandexecution.txt](https://github.com/HARPLab/DReyeVR/files/8188622/Ubuntu_Commandexecution.txt)

After the execution of the above commands I checked the Carla directory and located the config file at Unreal/CarlaUE4/Config/DReyeVRConfig.ini but could not see any updated flag related to LogUpdates. Attached is the config file. 

[DReyeVRConfigFile.txt](https://github.com/HARPLab/DReyeVR/files/8188638/DReyeVRConfigFile.txt)

**Comment by ajdroid** [comment] 2022-03-04 20:51
Hi, from the command execution log that you posted, it looks like the git pull failed, so you ended up re-installing the same old version. Please `git stash` your local changes before pulling and installing the new version

**Comment by Shroculus** [comment] 2022-03-04 20:59
> Hi, from the command execution log that you posted, it looks like the git pull failed, so you ended up re-installing the same old version. Please `git stash` your local changes before pulling and installing the new version

Thank you, now I can see the new flag LogUpdates which was set to false, but I have changed it to true. Do I need to now run the make PythonAPI and make launch again?

**Comment by ajdroid** [comment] 2022-03-04 21:04
Yes, please run make launch again and try to drive in the simulator

**Comment by Shroculus** [comment] 2022-03-04 21:16
I ran the make launch and command failed without launching the editor. 
(NOTE: I am currently running this without the Logitech device hence set both SRanipal and Logitech Plugin to false before the make launch) Below is the log and the file location screenshot for your reference. 

![image](https://user-images.githubusercontent.com/85901551/156842614-b0c1b675-4916-48c9-a1f4-1da826065108.png)

[Command_log.txt](https://github.com/HARPLab/DReyeVR/files/8188779/Command_log.txt)

**Comment by ajdroid** [comment] 2022-03-04 21:50
I'm not sure why this linker error is happening. Two checks:
1. Make sure you're running the x64 terminal in administrator mode
2. `make clean` and then `make launch` again

**Comment by GustavoSilvera** [comment] 2022-03-26 23:54
Hi @Shroculus do you have any updates on the status of this bug?

**Comment by Shroculus** [comment] 2022-03-29 16:24
Hi @GustavoSilvera : Apologies for not getting back to you with an update. Unfortunately even after following the previous steps the vehicle moves in the same way as before. 

However, when I checked the log files, I saw that the steering input from Logitech steering wheel fluctuated from -32767 to +32767 and nothing in between which I think might be the reason for crisscross movement of the vehicle. I am not sure if you can be of much help in this matter but do let me know if you know of the reason for the above said behavior of the steering wheel.

Thank you very much.

**Comment by GustavoSilvera** [comment] 2022-03-29 18:15
Interesting. The logitech wheel should smoothly transition from -32767 to +32767 so the fact that yours seems to be binary indicates to me there is something faulty with the hardware. The behaviour you demonstrated is explained by this but I'm not sure how to address the hardware problems. 

If the hardware is fully functional (there are other programs on Windows you can use to check this) then my only thought is that the mapping for the steering wheel is not correct for your model. In this case, you should change the input to `WheelRotation` in `AEgoVehicle::LogitechWheelUpdate()` to a value that is correctly mapped with the steering wheel.

**Comment by Shroculus** [comment] 2022-03-29 18:41
I have actually installed DReyeVR on 2 systems. System1 with exact same Logitech device and configurations works perfectly fine and the system2 does not. So I know the hardware is not faulty and the input doesn't necessarily require any changes since it worked completely fine with the system1. 

I have even checked the setting of both the systems they are the same and yet the problem persists.

**Comment by Shroculus** [comment] 2022-03-29 19:11
Commonalities:
1.  Both the systems are completely new with exact same configurations.
2. Windows 10 Enterprise - version 21H2
3.  Logitech G Hub installed (equipment detected and works fine in both the systems)
4. Same versions of CMake, Git, Make, 7Zip and Python (3.8.10)
5. Visual studio 2019 community version with Windows 10 SDK, x64 Visual c++ toolset and .NET framework 4.6.2
6. Unreal engine version 4.26
7. Exact system path variables as shown below

![image](https://user-images.githubusercontent.com/85901551/160687364-8f1cf157-a4f4-4c19-98ba-e808fe508e36.png)
![image](https://user-images.githubusercontent.com/85901551/160687739-ec904cab-bf42-48fc-b424-60afe44ba67a.png)

8. Logitech wheel plugin installed
9. SteamVR version 1.21.12 installed

Difference:
1. System 2 has VIVE wireless chip and the software installation but system 2 does not.

**Comment by GustavoSilvera** [comment] 2022-03-29 19:46
Hmm. Yeah everything seems in order so I'm not sure what might be causing this. The VIVE wireless chip certainly shouldn't have anything to do with this kind of issue. Have you tried cleanly removing and reinstalling Carla + DReyeVR on system 2 yet?

**Comment by Shroculus** [comment] 2022-03-29 19:51
I have completely uninstalled and reinstalled Carla + DReyeVR thrice on system 2, yet no luck.

**Comment by GustavoSilvera** [comment] 2022-05-18 00:03
Hi @Shroculus, could you check out the [upgrading-DReyeVR](https://github.com/HARPLab/DReyeVR/blob/main/Docs/Install.md#upgrading-dreyevr) section of the documentation to pull from `main` to get all the latest bugfixes. This issue should be fixed with those changes.

**Comment by GustavoSilvera** [comment] 2022-05-30 22:04
Due to lack of activity, I'll close this here. If it is still an issue feel free to reopen.

**Closed by GustavoSilvera** 2022-05-30 22:04 UTC
