### ISSUE TITLE
Custom props in dreyevr

### ISSUE THREAD

**Issue by RStorm98** [HARPLab/DReyeVR#103] opened 2023-04-17 12:41 UTC
Hello!

I'm curious as to how to go about importing props on DReyeVR in scenario_runner, since I can't seem to locate the folder that scenario runner spawns objects from. 
we have encountered this line of code in the scenario `object_crash_vehicle.py`: `'vehicle.diamondback.century'` but we are not sure where these attributes comes from:
```
212   first_vehicle = CarlaDataProvider.request_new_actor('vehicle.diamondback.century', transform) 
```

**Comment by GustavoSilvera** [comment] 2023-04-17 14:24
If you want to import static props, please [check out our tutorial](https://github.com/HARPLab/DReyeVR/blob/main/Docs/Signs.md) on how to add custom road signs to the world (as an example). 

To answer your question more specifically, the `vehicle.diamondback.century` is a C++ "identification tag" that is used to spawn the particular vehicle rather than any meaningful file path. All these vehicles are housed in `Unreal/CarlaUE4/Content/Carla/Blueprints/Vehicles/` and each blueprint has its own identification assigned to it so that you can filter the vehicles as `.filter("vehicle.*")` for example (this also applies to other actor types like [these](https://carla.readthedocs.io/en/latest/core_actors/#blueprints). 

For DReyeVR, we use a specific vehicle identification for our vehicles that follows `harplab.dreyevr_vehicle.*` to distinguish between carla vehicles and DReyeVR vehicles. 

Hope this helps!

**Comment by RStorm98** [comment] 2023-04-19 12:12
I apologize for the late reply, I got distracted with other tasks. 

We didn't succeed with importing custom props, but we found another solution.

**Closed as completed** 2023-04-25 12:03 UTC

**Comment by Nitro60zeus** [comment] 2023-09-03 15:51
Hi!! I went through the tutorial to add props. But while placing the prop, we need to open the project which is at `C:\carla\Build\UE4Carla\0.9.13-dirty\WindowsNoEditor\CarlaUE4\CarlaUE4.uproject` if I am not wrong. The issue is when I try to open it, it says missing c++ file, and I am not able to add prop :/

**Comment by Nitro60zeus** [comment] 2023-09-05 18:58
Ah ok, I figured out. Need to make all changes in `C:\carla\Unreal .... \CarlaUE4.uproject`. After that, in **x64 native tools command prompt** , run `make package` in the carla directory.
